name: build-push

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '*/5 * * * *'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  argocd-image:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: actions/checkout@v3

    - name: Set image tag
      run: |
        IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_RUN_NUMBER}-${GITHUB_SHA::8}
        echo "IMAGE_TAG=$IMAGE_TAG" >>$GITHUB_ENV

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_HOST }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.REGISTRY_HOST }}/pborntest/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Sign image
      uses: tamcore/cosign@master
      env:
        COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
        COSIGN_PASSWORD: ${{secrets.COSIGN_KEY_PASSWORD}}
      with:
        tags: |
          ${{ secrets.REGISTRY_HOST }}/pborntest/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
